export const normalWords = [
  "Cristiano Ronaldo",
  "Lionel Messi",
  "LeBron James",
  "Serena Williams",
  "Virat Kohli",
  "Roger Federer",
  "Tom Cruise",
  "Taylor Swift",
  "Beyoncé",
  "Elon Musk",
  "Manchester United",
  "Real Madrid",
  "Golden State Warriors",
  "Los Angeles Lakers",
  "FC Barcelona",
  "The Avengers",
  "Inception",
  "Interstellar",
  "Breaking Bad",
  "Game of Thrones",
  "The Dark Knight",
  "Harry Potter",
  "Star Wars",
  "Fast and Furious",
  "Black Panther",
  "Spider-Man",
  "Iron Man",
  "Rihanna",
  "Drake",
  "Justin Bieber",
  "Selena Gomez",
  "Cristiano Ronaldo",
  "Novak Djokovic",
  "Kylian Mbappé",
  "Neymar Jr",
  "Usain Bolt",
  "Michael Jordan",
  "Kobe Bryant",
  "Lewis Hamilton",
  "Max Verstappen",
  "New York Yankees",
  "Chicago Bulls",
  "Dallas Cowboys",
  "Miami Heat",
  "Brooklyn Nets",
  "The Godfather",
  "Titanic",
  "Avatar",
  "Oppenheimer",
  "Barbie",
// General & Cultural
  "Namaste",
  "DalBhat",
  "Chai",
  "Momo",
  "Everest",
  "Kathmandu",
  "Pokhara",
  "Himalaya",
  "Dashain",
  "Tihar",
  "Diwali",
  "Holi",
  "Buddha",
  "Shiva",
  "Ganesh",
  "Mandir",
  "Stupa",
  "Curry",
  "Roti",
  "Biryani",
  "Lassi",
  "Puja",
  "Thali",
  "DhakaTopi",
  "Pashupatinath",
  "Lumbini",
  "Varanasi",
  "Banaras",
  "Rickshaw",
  "Mehendi",
  "Sari",
  "Bindi",
  "Sindoor",
  "Karma",
  "Mantra",
  "Raga",
  "Kathaa",

  // Indian Actors
  "ShahRukhKhan",
  "SalmanKhan",
  "AamirKhan",
  "RanbirKapoor",
  "RanveerSingh",
  "HrithikRoshan",
  "AkshayKumar",
  "AjayDevgn",
  "AmitabhBachchan",
  "Rajinikanth",
  "Prabhas",
  "AlluArjun",
  "VijayDeverakonda",
  "Yash",
  "MaheshBabu",
  "KartikAaryan",
  "VickyKaushal",
  "AyushmannKhurrana",
  "SidharthMalhotra",
  "TigerShroff",
  "Dhanush",

  // Indian Actresses
  "DeepikaPadukone",
  "PriyankaChopra",
  "AliaBhatt",
  "KareenaKapoor",
  "KatrinaKaif",
  "AnushkaSharma",
  "ShraddhaKapoor",
  "KiaraAdvani",
  "JanhviKapoor",
  "MadhuriDixit",
  "VidyaBalan",
  "SamanthaRuthPrabhu",
  "Nayanthara",
  "KajalAggarwal",
  "RashmikaMandanna",

  // Movie Names
  "Sholay",
  "DilwaleDulhaniaLeJayenge",
  "KabhiKhushiKabhieGham",
  "3Idiots",
  "PK",
  "Dangal",
  "BajrangiBhaijaan",
  "ChennaiExpress",
  "Bahubali",
  "KGF",
  "Pushpa",
  "RRR",
  "Jawan",
  "Pathaan",
  "Gadar",
  "Lagaan",
  "ZindagiNaMilegiDobara",
  "Barfi",
  "Andhadhun",
  "Tamasha",
  "Rockstar",
  "Bahubali2",
  "Drishyam",
  "GullyBoy",
  "Don",
  "War",
  "Tanhaji",
  "KabirSingh",
  "Animal",

  // Nepali Movies & Celebs
  "ChhakkaPanja",
  "Kabaddi",
  "PremGeet",
  "DayahangRai",
  "SaugatMalla",
  "AnmolKC",
  "SwastimaKhadka",
  "PriyankaKarki",
  "Momo", "DalBhat", "Chowmein", "Samosa", "Pakora", "PaniPuri", "Biryani", "Roti", "Chai",
  "Lassi", "Thukpa", "Gundruk", "SelRoti", "Achar", "Jalebi", "Malai", "Chowk", "Dhokla",
  "Idli", "Dosa", "VadaPav", "RajmaChawal", "ButterChicken",

  // Places
  "Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Delhi", "Mumbai", "Chennai", "Bangalore",
  "Hyderabad", "Jaipur", "Goa", "Darjeeling", "Varanasi", "Lumbini", "Pashupatinath", "Everest",
  "Thamel", "Patan", "Nagarkot", "Swayambhu",

  // Actors & Celebs
  "ShahRukhKhan", "SalmanKhan", "AamirKhan", "RanbirKapoor", "RanveerSingh", "Prabhas", "AlluArjun",
  "Yash", "Vijay", "Rajinikanth", "AmitabhBachchan", "HrithikRoshan", "AkshayKumar", "DayahangRai",
  "SaugatMalla", "AnmolKC", "SwastimaKhadka", "PriyankaKarki", "ReechaSharma", "RajeshHamal",

  // Movies
  "Bahubali", "RRR", "Jawan", "Pathaan", "3Idiots", "Dangal", "KGF", "Pushpa", "Drishyam",
  "Lagaan", "DilSe", "Rockstar", "Tamasha", "Barfi", "KabirSingh", "Animal", "ChhakkaPanja",
  "Kabaddi", "PremGeet", "Loot", "KaloPothi",

  // Festivals
  "Dashain", "Tihar", "Diwali", "Holi", "BisketJatra", "IndraJatra", "Teej", "Chhath", "MagheSankranti",
  "JanaiPurnima", "RakshaBandhan", "MahaShivaratri",

  // Religious & Cultural
  "Mandir", "Stupa", "PrayerFlag", "Buddha", "Shiva", "Ganesh", "Karma", "Mantra", "Namaste",
  "Yatra", "Aarti", "Puja", "DhakaTopi", "Sari", "Bindi", "Tikka", "Sindoor", "Pashmina",

  // Random Fun / Everyday
  "Rickshaw", "Auto", "Tempo", "Bajaj", "Cricket", "Bollywood", "Tollywood", "Kollywood",
  "DesiVibes", "ChiyaGuff", "Adda", "Chill", "Bhai", "Didi", "Sathi", "Jindagi", "Khatra",
  "Aba", "Hera", "BalleBalle", "ThuloManche", "Chhoro", "KetaKeti", "Mitra", "SathiHaroo",
  "Tyo", "Huncha", "Ramro", "Mitho", "Sundar", "Dherai", "Aaram"



];
